name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        asset_name: 
          - mqc_versions_table-linux-amd64
        version:
          - stable
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -qy install make build-essential libtool autoconf grep upx binutils musl-tools
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: "Build musl statically linked binary"
      run: |
        nimble musl
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mqc_versions_table
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
